s3_env: &s3_env
  TF_BACKEND_CONFIG_access_key: ((((foundation))/s3_access_key_id))
  TF_BACKEND_CONFIG_endpoint:  ((((foundation))/s3_endpoint))
  TF_BACKEND_CONFIG_region: ((((foundation))/s3_region_name))
  TF_BACKEND_CONFIG_secret_key: ((((foundation))/s3_secret_access_key))
  TF_BACKEND_CONFIG_key: "terraforming-dps/terraform.tfstate"
  TF_BACKEND_CONFIG_skip_requesting_account_id: true
  TF_BACKEND_CONFIG_skip_credentials_validation: true
  TF_BACKEND_CONFIG_skip_get_ec2_platforms: true
  TF_BACKEND_CONFIG_skip_metadata_api_check: true
  TF_BACKEND_CONFIG_skip_region_validation: true
  TF_BACKEND_CONFIG_force_path_style: true

resources:
  - name: concourse-terraform
    type: git
    source:
      uri: https://github.com/Snapkitchen/concourse-terraform
  - name: concourse-terraform-image
    type: docker-image
    source:
      repository: snapkitchen/concourse-terraform
      tag: 0.12.21
  - name: terraforming-dps
    tags: ((tags))
    icon: git
    type: git
    check_every: 10m  
    source:  
      uri: https://github.com/bottkars/terraforming-dps.git
      branch: master
    
jobs:
  # a job using a terraform task with the terraform image
  - name: terraform-task
    plan: 
    - get: concourse-terraform
    - get: concourse-terraform-image
    - get: terraforming-dps
    - task: terraform-plan
      image: concourse-terraform-image
      file: concourse-terraform/tasks/plan.yaml
      input_mapping:
        terraform-source-dir: terraforming-dps
      params:
          TF_VAR_env_name: "dps_demo"
          TF_VAR_location: "West Europe"
          TF_VAR_dns_suffix: "dpslab.labbuildr.com"
          TF_VAR_ddve_hostname: "ddve1"
          TF_VAR_ddve_meta_disk_size: 1023
          TF_VAR_ddve_meta_disks:  '["1","2"]'
          TF_VAR_ddve_initial_password: "Change_Me12345_"
          TF_VAR_ddve_vm_size: "Standard_F4"
          TF_DIR_PATH: terraforming_ddve
          TF_VAR_subscription_id: ((azure_dell_subscription_id))
          TF_VAR_tenant_id: ((azure_dell_tenant_id))
          TF_VAR_client_id: ((azure_dell_client_id))
          TF_VAR_client_secret: ((azure_dell_client_secret))
            
          <<: *s3_env