variable "gcp_project" {
  default     = null
  description = "the GCP Project do deploy resources"

}

//variable "gcp_credentials" {
//  type        = string
//  description = "service account credentials are credentials downloaded from Cloud Console or generated by gcloud"
//}
variable "create_s2svpn" {
  type        = bool
  default     = false
  description = "Should a Side 2 Side VPN Gateway be deployed"
}
variable "create_gke" {
  type        = bool
  default     = false
  description = "deploy a basic Google Kubernetes Engine for test/dev"
}
variable "create_cloud_nat" { default = false }
variable "create_ddve_project_role" {
  type        = bool
  default     = false
  description = "deploy a role for ddev oauth to Goocle Cloud Storage"
}
variable "ddve_role_id" {
  default     = "ddve_oauth_role"
  type        = string
  description = "id of the role fo DDVE used or be deployed"
}

// routable S2S Target (you location) addresses 
variable "s2s_vpn_route_dest" {
  type        = list(string)
  default     = ["127.0.0.1/32"]
  description = "Routing Destination ( on Premises local networks ) for VPN"
}
variable "vpn_shared_secret" {
  type        = string
  description = "Shared Secret for VPN Connection"
  default     = "topsecret12345"
}
variable "vpn_wan_ip" {
  default     = "0.0.0.0"
  type        = string
  description = "IP Adress of the Local VPN Gateway"
}
variable "gke_num_nodes" {
  default     = 2
  type        = number
  description = "Number of GKE Worker Nodes"
}
variable "gke_zonal" { 
  default = true 
  type        = bool
  description = "deployment Zonal Model used for GKE"
  }
variable "labels" {
  type    = map(any)
  default = {}
  description = "Key Value of labels you want to apply to Resources"

}
variable "ENV_NAME" { 
  default = "demo" 
    description = "Enfironment Name, concatenated to resource names"

  }

