resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest      

resources:
- name: terraform
  type: terraform
  source:
    env_name: ((ENV))
    backend_type: s3
    backend_config:
      access_key: ((((foundation))/s3_access_key_id))
      endpoint:  ((((foundation))/s3_endpoint))
      region: ((((foundation))/s3_region_name))
      secret_key: ((((foundation))/s3_secret_access_key))
      key: "terraforming-dps/terraforming-gcp/terraform.tfstate"
      bucket: "terraform"      
      skip_credentials_validation: true
      skip_metadata_api_check: true
      skip_region_validation: true
      force_path_style  : true

- name: terraforming-dps
  tags: ((tags))
  icon: git
  type: git
  check_every: 10m  
  source:  
    uri: https://github.com/bottkars/terraforming-dps.git
    branch: main

jobs:
- name: terraform-plan
  plan:
  - get: terraforming-dps
  - put: terraform 
    params:
      env_name: ((ENV))
      terraform_source: terraforming-dps/terraforming-gcp
      plan_only: true
      vars: ((GCP.prod))

- name: terraform-apply
  plan:
  - get: terraforming-dps
    trigger: false
    passed: [terraform-plan]
  - get: terraform
    trigger: false
    passed: [terraform-plan]
  - put: terraform
    params:
      env_name: ((ENV))
      terraform_source: terraforming-dps/terraforming-gcp
      plan_run: true

- name: terraform-destroy
  plan:
    - get: terraforming-dps
    - put: terraform
      params:
        terraform_source: terraforming-dps/terraforming-gcp
        env_name: ((ENV))
        action: destroy
        vars: ((GCP.prod))
      get_params:
        action: destroy